### ISSUE TITLE
Connect() does not return bool

### ISSUE THREAD

**Issue by belld19233** [Mecademic/mecademicpy#1]
Wiki says connect() should return True if connection is successful, but there is no return in the function

**Comment by gbmecademic** [comment]
Hello,
Thank you for noticing, I will submit the change to our team and it will be updated in the next release comming soon.

**Comment by gbmecademic** [comment]
The documentation was fixed and say that the robot will raise an error if the connection cannot be established.

**Comment by belld19233** [comment]
Thanks! You were so swift I completely forgot about this
