### ISSUE TITLE
1.4.0 not compatible with FW 8.3 and up

### ISSUE THREAD

**Issue by cBeaur** [Mecademic/mecademicpy#13]
I had FW 8.4 and python lib 1.4.0 and had the error :
Received robot error 1001 (MX_ST_UNKWNOWN_CMD) : Empty command or command unrecognized. - Command: 'ResetPStop2'.
Had to update my meca500 R3 to the latest update 9.3.4.6195 to make it work.
So it is not 8.3 and up.

**Comment by gbmecademic** [comment]
You're right. The mecademicpy framework sends ResetPStop2 command to the robot whenever your application calls ResetPStop2 (or legacy ResetPStop) method, regardless the robot version. 
Unfortunately older robot only support the legacy ResetPStop command name.

In the next mecademicpy release we'll make sure to use legacy command name ResetPStop when connected to older robots.

In the mean time, if you have to downgrade your robot to release 8.4 you can replace calls to robot.ResetPStop2 (or robot.ResetPStop) in your application by this command:
robot.SendCustomCommand('ResetPStop')

Thanks for reporting the issue!

**Comment by gbmecademic** [comment]
This was fixed in the 2.0 release.
