### ISSUE TITLE
Socket timeout in _connect_socket is too short

### ISSUE THREAD

**Issue by michaelwyiu** [Mecademic/mecademicpy#14]
Hello, the default socket time is a bit too short for me to successfully connect to my robot.

I saw that the default loop time is 100 ms, but the timeout time is set to loop_timeout_ms / 1000 ->100 ms.

In the next update, is it possible to see a change that would allow greater customization? For example the ability to specify total timeout time, looping timeout time, and number of loops to attempt.

**Comment by gbmecademic** [comment]
Hello,
Thank you for opening this issue. This will be addressed in the next update. I will close this issue once the update is available.

**Comment by gbmecademic** [comment]
This was addressed in the 2.0 release.
